/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "grpc-helloworld"
include("grpc-helloworld-common")
include("grpc-helloworld-server")
include("grpc-helloworld-client")
